package com.manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.List;

import com.model.Czesc;

public class CzescManager {
	private Connection conn;
	private Statement stmt;

	private PreparedStatement DodajCzesc;
	private PreparedStatement UsunCzesc;
	private PreparedStatement UsunWszystkieCzesc;
	private PreparedStatement GetCzesc;
	private PreparedStatement GetCzescid;
	private PreparedStatement listaCzesc;
	private PreparedStatement UpdateCzesc;

	public CzescManager() {
		try {
			conn = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");
			stmt = conn.createStatement();
			ResultSet rs = conn.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Czesc".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			if (!tableExists)
				stmt.executeUpdate("Create table Czesc (idCzesc int GENERATED BY DEFAULT AS IDENTITY, numerczesci varchar(15), nazwa varchar(50), cena double,zamowinie_id int,  FOREIGN KEY(zamowienie_id) REFERENCES Zamowienie(idZamowienie) )");
			DodajCzesc = conn.prepareStatement("INSERT INTO Czesc(numerczesci, nazwa, cena ) VALUES (?,?,?)");
			UsunCzesc = conn.prepareStatement("DELETE FROM Czesc WHERE numerczesci = ?");
			UsunWszystkieCzesc = conn.prepareStatement("DELETE FROM Czesc");
			GetCzesc = conn.prepareStatement("SELECT * FROM Czesc WHERE numerczesci = ?");
			GetCzescid = conn.prepareStatement("SELECT * FROM Czesc WHERE idCzesc = ?");
			listaCzesc = conn.prepareStatement("SELECT * FROM Czesc");
			UpdateCzesc = conn.prepareStatement("Update Czesc SET numerczesci = ?, nazwa = ?, cena = ? WHERE numerczesci = ?");

		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	
	public Connection getConnection() {
		return conn;
	}

	
	public boolean DodajCzesc(Czesc czesc) {
		int licznik = 0;
		try {
			DodajCzesc.setString(1, czesc.getNumerCzesci());
			DodajCzesc.setString(2, czesc.getNazwa());
			DodajCzesc.setDouble(3, czesc.getCena());
			licznik = DodajCzesc.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		if(licznik == 1) return true;
		else return false;
	}
	
	//dodawnie listy
	public boolean DodajkilkaCzesc(List<Czesc> czesci ) {
		
		try {
			conn.setAutoCommit(false);
			for(Czesc czesc: czesci){
			DodajCzesc.setString(1, czesc.getNumerCzesci());
			DodajCzesc.setString(2, czesc.getNazwa());
			DodajCzesc.setDouble(3, czesc.getCena());
			DodajCzesc.executeUpdate();
			}
			conn.commit();
			conn.setAutoCommit(true);
		} catch (SQLException e) {
			try{
				conn.rollback();
				conn.setAutoCommit(true);
			}catch (SQLException ee) {
			ee.printStackTrace();
		}
		}
		 return false;
	}

	
	public boolean UsunCzesc(Czesc czesc) {
		int licznik = 0;
		try {
			
			UsunCzesc.setString(1, czesc.getNumerCzesci());
			licznik = UsunCzesc.executeUpdate();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		if(licznik == 1) return true;
		else return false;
	}

	
	public void UsunWszystkieCzesc() {
		
		try {
			
			UsunWszystkieCzesc.executeUpdate();
			
		} catch (SQLException e) {
			e.printStackTrace();
		}
		
	}

	
	public int UpdateCzesc(String czescstara, Czesc czescnowa) {
		int licznik = 0;
		try {
			conn.setAutoCommit(false);
			UpdateCzesc.setString(1, czescnowa.getNumerCzesci());
			UpdateCzesc.setString(2, czescnowa.getNazwa());
			UpdateCzesc.setDouble(3, czescnowa.getCena());
			UpdateCzesc.setString(5, czescstara);
			licznik = UpdateCzesc.executeUpdate();
			conn.commit();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return licznik;
	}

	
	public List<Czesc> getAll() {
		List<Czesc> czesci = new ArrayList<Czesc>();
		try {
			ResultSet rs = listaCzesc.executeQuery();
			while (rs.next()) {
				Czesc cz = new Czesc();
				cz.setIdCzesc(rs.getInt("idCzesc"));
				cz.setNumerCzesci(rs.getString("numerczesci"));
				cz.setNazwa(rs.getString("nazwa"));
				cz.setCena(rs.getDouble("cena"));
				czesci.add(cz);
				
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return czesci;
	}

	
	public Czesc getNumerCzesc(String numerczesci) {
		Czesc czesci = new Czesc();
		try {
			GetCzesc.setString(1, numerczesci);
			ResultSet rs = GetCzesc.executeQuery();
			while (rs.next()) {
				czesci.setIdCzesc(rs.getInt("idCzesc"));
				czesci.setNumerCzesci(rs.getString("numerczesci"));
				czesci.setNazwa(rs.getString("nazwa"));
				czesci.setCena(rs.getDouble("cena"));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return czesci;
	}

	
	public Czesc getidCzesc(String idczesc) {
		Czesc czesci = new Czesc();
		try {
			GetCzescid.setString(1, idczesc);
			ResultSet rs = GetCzescid.executeQuery();
			while (rs.next()) {
				czesci.setIdCzesc(rs.getInt("idCzesc"));
				czesci.setNumerCzesci(rs.getString("numerczesci"));
				czesci.setNazwa(rs.getString("nazwa"));
				czesci.setCena(rs.getDouble("cena"));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return czesci;
	}
}