package manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;


import model.Czesc;

public class CzescManager {
	private Connection conn;
	private Statement stmt;
	
	private PreparedStatement DodajCzesc;
	private PreparedStatement UsunCzesc;
	private PreparedStatement UsunWszystkieCzesc;
	private PreparedStatement GetCzesc;
	private PreparedStatement GetCzescid;
	private PreparedStatement listaCzesc;
	
	public CzescManager(){
		try{
			conn = DriverManager.getConnection("jdbc:hsqldb:hsql://localhost/workdb");
			stmt = conn.createStatement();
			ResultSet rs = conn.getMetaData().getTables(null, null, null, null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Czesc".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}
			if (!tableExists) stmt.executeUpdate("Create table Czesc (idCzesc int UNIQUE GENERATED BY DEFAULT AS IDENTITY, nazwa varchar(50), cena money, marka varchar(20) )");
			DodajCzesc = conn.prepareStatement("INSERT INTO Czesc(nazwa, cena ,marka) VALUES (?,?,?)");
			UsunCzesc = conn.prepareStatement("DELETE FROM Czesc WHERE idCzesc = ?");
			UsunWszystkieCzesc = conn.prepareStatement("DELETE FROM Czesc");
			GetCzesc = conn.prepareStatement("SELECT * FROM Czesc WHERE nazwa = ?");
			GetCzescid = conn.prepareStatement("SELECT * FROM Czesc WHERE idCzesc = ?");
			listaCzesc = conn.prepareStatement("SELECT * FROM Czesc");
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}
	
	public Connection getConnection() {
		return conn;
	}
	
	public int DodajCzesc(Czesc czesc){
	int licznik = 0;
		try {
			conn.setAutoCommit(false);
			DodajCzesc.setString(1, czesc.getNazwa());
			DodajCzesc.setDouble(2, czesc.getCena());
			DodajCzesc.setString(3, czesc.getMarka());
			licznik = DodajCzesc.executeUpdate();
			conn.commit();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	return licznik;
	}
	
	public int UsunCzesc(Czesc czesc){
	int licznik = 0;
		try {
			conn.setAutoCommit(false);
			UsunCzesc.setInt(1, czesc.getIdCzesc());
			licznik = UsunCzesc.executeUpdate();
			conn.commit();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	return licznik;
	}
	
	public int UsunWszystkieCzesc(Czesc czesc){
	int licznik = 0;
		try {
			conn.setAutoCommit(false);
			licznik = UsunWszystkieCzesc.executeUpdate();
			conn.commit();
		} catch (SQLException e) {
			e.printStackTrace();
		}
	return licznik;
	}
	
	//dodaj jakas liste tu
	
}	