package Manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class ZamowienieManager {
	
	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	

	private String createTableCzesc = "Create table Czesc (idCzesc int GENERATED BY DEFAULT AS IDENTITY, nazwa varchar(50), cena money, marka varchar(20) )";
	
	private String createTableZamowienie = "Create table Zamowienie (idZamowienie int GENERATED BY DEFAULT AS IDENTITY, kontrahent varchar(50), suma money, dataZamowienia date )";
	
	private Statement statement;
	
	public ZamowienieManager() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableCzesc);
				statement.executeUpdate(createTableZamowienie);

		
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}

}
