package Manager;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class ZamowienieManager {
	
	private Connection connection;

	private String url = "jdbc:hsqldb:hsql://localhost/workdb";
	

	private String createTableCzesc = "Create table Czesc (idCzesc int GENERATED BY DEFAULT AS IDENTITY, nazwa varchar(50), cena money, marka varchar(20) )";
	
	private String createTableZamowienie = "Create table Zamowienie (idZamowienie int GENERATED BY DEFAULT AS IDENTITY,kontrahent varchar(50), suma money, dataZamowienia date )";
	
	private String createTableCzescHasZamowienie = "Create table Czesc_has_Zamowienie ( czesc_idCzesc, zamowienie_idZamowienie)";
	
	private PreparedStatement DodajCzescStmt;
	private PreparedStatement DodajZamowienieStmt;
	private PreparedStatement UsunCzescStmt;
	private PreparedStatement WyswietCzesc;
	private Statement statement;
	
	public ZamowienieManager() {
		try {
			connection = DriverManager.getConnection(url);
			statement = connection.createStatement();

			ResultSet rs = connection.getMetaData().getTables(null, null, null,
					null);
			boolean tableExists = false;
			while (rs.next()) {
				if ("Person".equalsIgnoreCase(rs.getString("TABLE_NAME"))) {
					tableExists = true;
					break;
				}
			}

			if (!tableExists)
				statement.executeUpdate(createTableCzesc);
				statement.executeUpdate(createTableZamowienie);
				
				DodajCzescStmt = connection
						.prepareStatement("INSERT INTO Czesc (FKidZamowienia, nazwa, cena, marka) VALUES (?, ?, ?, ?)");
				DodajZamowienieStmt = connection
						.prepareStatement("INSERT INTO Zamowienie (, cena, marka) VALUES (?, ?, ?)");
				//deleteAllPersonsStmt = connection
						//.prepareStatement("DELETE FROM Person");
				//getAllPersonsStmt = connection
						//.prepareStatement("SELECT id, name, yob FROM Person");
//
		
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	Connection getConnection() {
		return connection;
	}
	
	public static void main(String[] args) {
		
	
	}

}
